openapi: "3.0.3"
info:
  title: "Project API"
  description: "⚡ Personal Self-Hosted REST API Service."
  version: "${project.version}"
servers:
  - url: "https://projecttl.net"
#  - url: "http://localhost:3000"
paths:
#  /:
#    get:
#      description: "Hello World!"
#      responses:
#        "200":
#          description: "OK"
#          content:
#            text/html:
#              examples:
#                Example#1:
#                  value: "Hello World!"
components:
  schemas: {}