services:
  api:
    container_name: "project_api"
    image: "project_api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./server.log:/opt/app/server.log"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
